<?php

return [
    'permissions' => [
        'updateOrganization' =>'Manage Organization',
        'employeeDepartment' => 'employee Department',
        'employee' => 'employee',
        'department' => 'department',
        'projects' => 'projects',
        'enginering' => 'enginering',
        'space' => 'space',
        'banks' => 'banks',
        'suppliers' => 'suppliers',
        'orginzation' => 'orginzation',
        'dev_equp' => 'dev_equp',
        'vehicles' => 'vehicles',
        'buildings' => 'buildings',
        'Gardens_lands' =>'Gardens_lands',
        'warehouses' => 'warehouses',
        'subscribers' => 'subscribers',
        'agenda_report' => 'agenda_report',
        'offices_orginzatos' => 'offices_orginzatos',
        'assets' => 'assets',
        'archieve' => 'archieve',
        'out_archieve' => 'out_archieve',
        'in_archieve' => 'in_archieve',
        'mun_archieve' => 'mun_archieve',
        'proj_archieve' =>'proj_archieve',
        'emp_archieve' => 'emp_archieve',
        'dep_archieve' => 'dep_archieve',
        'cit_archieve' => 'cit_archieve',
        'lic_archieve' => 'lic_archieve',
        'licFile_archieve' => 'licFile_archieve',
        'jobLic_archieve' => 'jobLic_archieve',
        'agenda_archieve' => 'agenda_archieve',
        "reports" => 'reports',
        'report_archieve' => 'report_archieve',
        "permissions" => 'permissions',
        "account" => 'account',
        "my_account" => 'my_account',
        
        "store_archive"=> 'store_archive',
        "archive_delete"=> 'archive_delete',
        
        "edit_model"=> 'edit_model',
        "delete_model"=> 'delete_model',
        "dailyReport"=> 'dailyReport',
        "volunteer" => 'Volunteers',
        'jal_archieve' => 'jal_archieve',
        
        "building_permits" => 'building_permits',
        'electricity_icon' => 'electricity_icon',
        "water_icon" => 'water_icon',
        "sub_archives" => 'sub_archives',
        "sub_report" => 'sub_report',
        "letter_licenses" => 'letter_licenses',
        "licence_icon" => 'licence_icon',
        "report_icon" => 'report_icon',

        "waterApp" => 'waterSubscription',
        "elecApp" => 'elecSubscription',
        'empOutArchive1'=>'empOutArchive1',
        ]

];
